# Generated by Django 4.2.6 on 2023-11-03 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0003_alter_evento_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presupuesto', models.FloatField(verbose_name='Presupuesto')),
                ('transporte', models.FloatField(verbose_name='Trasporte')),
                ('personal', models.FloatField(verbose_name='Personal')),
                ('combustible', models.FloatField(verbose_name='Combustible')),
                ('alquiler', models.FloatField(verbose_name='Alquiler')),
                ('viaticos', models.FloatField(verbose_name='Viaticos')),
                ('donaciones', models.FloatField(verbose_name='Donaciones')),
                ('otros', models.FloatField(verbose_name='Otros')),
                ('totalgastado', models.FloatField(verbose_name='Totalgastado')),
                ('residuo', models.FloatField(verbose_name='Residuo')),
                ('eventoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.evento')),
            ],
            options={
                'verbose_name': 'gasto',
                'verbose_name_plural': 'gastos',
                'db_table': 'gasto',
                'ordering': ['-id'],
            },
        ),
    ]
