# Generated by Django 4.2.6 on 2023-10-11 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estadocivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'estadocivil',
                'verbose_name_plural': 'estadosciviles',
                'db_table': 'estadocivil',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'genero',
                'verbose_name_plural': 'generos',
                'db_table': 'genero',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'nacionalidad',
                'verbose_name_plural': 'nacionalidades',
                'db_table': 'nacionalidad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('di', models.CharField(max_length=50, verbose_name='Di')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('telefono', models.CharField(max_length=50, verbose_name='Telefono')),
                ('correo', models.EmailField(max_length=50, verbose_name='Correo')),
                ('nohijos', models.CharField(max_length=50, verbose_name='Nohijos')),
                ('estadocivil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miembros.estadocivil')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miembros.genero')),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miembros.nacionalidad')),
            ],
            options={
                'verbose_name': 'miembro',
                'verbose_name_plural': 'miembros',
                'db_table': 'miembro',
                'ordering': ['id'],
            },
        ),
    ]
