# Generated by Django 4.2.6 on 2023-10-22 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0002_miembro_edad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miembro',
            options={'ordering': ['-id'], 'verbose_name': 'miembro', 'verbose_name_plural': 'miembros'},
        ),
    ]
