# Generated by Django 4.2.6 on 2023-11-03 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('miembros', '0003_alter_miembro_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Nombre')),
                ('fecha', models.DateField(max_length=25)),
                ('sheij', models.CharField(max_length=100, verbose_name='Sheij')),
                ('novio', models.CharField(max_length=100, verbose_name='Novio')),
                ('novia', models.CharField(max_length=100, verbose_name='Novia')),
                ('guardian', models.CharField(max_length=100, verbose_name='Guardian')),
                ('testigos', models.CharField(max_length=350, verbose_name='Testigos')),
            ],
            options={
                'verbose_name': 'acta',
                'verbose_name_plural': 'actas',
                'db_table': 'acta',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'db_table': 'categoria',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'clase',
                'verbose_name_plural': 'clases',
                'db_table': 'clase',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
                'db_table': 'curso',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='maestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'maestro',
                'verbose_name_plural': 'maestros',
                'db_table': 'maestro',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'status',
                'verbose_name_plural': 'statuses',
                'db_table': 'status',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='tiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'tiempo',
                'verbose_name_plural': 'tiempos',
                'db_table': 'tiempo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='noactividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('fechainicio', models.DateField(max_length=25)),
                ('fechafin', models.DateField(max_length=25)),
                ('duracion', models.IntegerField(verbose_name='Duracion')),
                ('edad', models.CharField(default=0, max_length=10, verbose_name='Edad')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.categoria')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.clase')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.curso')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maestro', to='actividades.maestro')),
                ('nacionalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nacion', to='miembros.nacionalidad')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.status')),
                ('tiempo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.tiempo')),
            ],
            options={
                'verbose_name': 'noactividad',
                'verbose_name_plural': 'noactividades',
                'db_table': 'noactividad',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechainicio', models.DateField(max_length=25)),
                ('fechafin', models.DateField(max_length=25)),
                ('duracion', models.IntegerField(verbose_name='Duracion')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.categoria')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.clase')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.curso')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_maestro', to='actividades.maestro')),
                ('miembroa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_miembroa', to='miembros.miembro')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.status')),
                ('tiempo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.tiempo')),
            ],
            options={
                'verbose_name': 'actividad',
                'verbose_name_plural': 'actividades',
                'db_table': 'actividad',
                'ordering': ['-id'],
            },
        ),
    ]
